# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gitploy 0.2.2 ruby lib

Gem::Specification.new do |s|
  s.name = "gitploy"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Brent Dillingham", "Mike Glenn"]
  s.date = "2016-01-01"
  s.description = "Dead-simple deployments. No, for real this time."
  s.email = ["brentdillingham@gmail.com", "mglenn@ilude.com"]
  s.executables = ["gitploy"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/gitploy",
    "features/gitploy.feature",
    "features/step_definitions/gitploy_steps.rb",
    "features/support/env.rb",
    "gitploy.gemspec",
    "lib/gitploy.rb",
    "lib/gitploy/script.rb",
    "spec/gitploy_config_spec.rb",
    "spec/gitploy_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/brentd/gitploy"
  s.rubygems_version = "2.4.4"
  s.summary = "Deployment DSL created with git in mind"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<aruba>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<aruba>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<aruba>, [">= 0"])
  end
end

